### ISSUE TITLE
PID calibration and dynamic wind rectification.

### ISSUE THREAD

**Issue by serbeeq8** [serbeeq8/iotuav#4]

**Comment by Srinjoy2002** [comment]
### Wind Rectification for Drone Navigation

To ensure our drone could accurately spray weeds despite windy conditions, we relied on fundamental principles of physics and real-time adjustments. Here's how we did it:

#### Physics Principles:
1. **Newton's Laws of Motion:** These laws helped us understand how the drone moves and reacts to forces, like wind pushing it off course.
2. **Stokes' Law:** This law was key for calculating the drag force, or resistance, the drone experiences as it moves through the air.

#### Breaking Down the Wind:
We started by figuring out the wind speed and direction. By breaking the wind into its horizontal components, we could see exactly how it would push the drone.

#### Adjusting for Wind:
Using Stokes' Law, we calculated the drag force the wind would exert on the drone. With these calculations, we could predict how much the drone would be pushed off its intended path during its flight.

#### Correcting the Path:
We adjusted the drone's target coordinates to counteract the wind's push. This means we told the drone to aim for slightly different spots so that, when the wind pushed it, it would end up exactly where it needed to be.

#### Real-Time Monitoring:
As the drone flew, we used real-time data to track its position and make continuous adjustments. This ensured that any unexpected changes in wind could be quickly corrected, keeping the drone on course.

#### Visualization:
To make it all visible, we used Turtle graphics in the AirSim simulation. This allowed us to see the original weed positions, the adjusted target points, and the drone's actual path. It was like drawing a map of how the drone should fly and then watching it in real-time.

By combining these physical principles and real-time adjustments, we made sure our drone could accurately navigate and spray weeds, even in windy conditions. This approach shows how applying theoretical physics can solve practical problems in autonomous navigation and make tasks like weed spraying more efficient and reliable.
